### PR TITLE
Search

### PR DESCRIPTION
**Pull request by MirnaBenyamine**
I'm done with my task #12.
I need @Ericphilippe  to review my code, @marinasamy  to review my documentation and @SeifKeshk to review my scenarios.

### CODE REVIEW

**Comment by marinasamy** [comment]
Everything is great @MirnaBenyamine .

**Comment by SeifKeshk** [comment]
Good Job @MirnaBenyamine

**Comment by SeifKeshk** [comment]
@MirnaBenyamine  Well done, but please check the fail scenario

**Comment by Ericphilippe** [comment]
@MirnaBenyamine The code is working.

**Pull request merged**
