### PR TITLE
Edit profile

### PR DESCRIPTION
**Pull request by MirnaBenyamine**
Edit Profile task is done #42 , I would like @Ericphilippe  to review my documentation, @marinasamy to review scnario and @NohaGomaa  to review my code.
Show statistics task is also done #41 , I would like @NohaGomaa  to review my documentation, @DonaKaid  to review scnario and @Ericphilippe to review my code

### CODE REVIEW

**Comment by marinasamy** [comment]
https://github.com/GUC-SE-2015/workout-tracker/labels/Scenario-Reviewer
great Job Mirna !

**Comment by marinasamy** [comment]
Scenario-Reviewer 
great Job Mirna !

**Comment by NohaGomaa** [comment]
Documentation for  task #41 approved

**Comment by marinasamy** [comment]
Scenario is great #42

**Comment by NohaGomaa** [comment]
Code for task #42 is reviewed and approved

**Pull request closed without merging**
